Models/ErrorViewModel.cs
using System;

namespace ReceitasMvc.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Receita.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ReceitasMvc.Models
{
    public class Receita
    {
        public int Id { get; set; }

        [Required, StringLength(150), Display(Name = "Nome da receita")]
        public string Titulo { get; set; }
        [Required, StringLength(5000), Display(Name = "Modo de preparo")]
        public string Preparo { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ReceitasMvc.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ReceitasMvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ReceitasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReceitasMvc.Data;
using ReceitasMvc.Models;

namespace ReceitasMvc.Controllers
{
    public class ReceitasController : Controller
    {
        private readonly ReceitasMvcContext _context;

        public ReceitasController(ReceitasMvcContext context)
        {
            _context = context;
        }

        // GET: Receitas
        public async Task<IActionResult> Index(string searchString)
        {
            var receitas = from r in _context.Receita
                           select r;

            if (!String.IsNullOrEmpty(searchString))
            {
                receitas = receitas.Where(s => s.Titulo.Contains(searchString));
            }
            return View(await receitas.ToListAsync());
           // return View(await _context.Receita.ToListAsync());
        }

        // GET: Receitas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receita = await _context.Receita
                .FirstOrDefaultAsync(m => m.Id == id);
            if (receita == null)
            {
                return NotFound();
            }

            return View(receita);
        }

        // GET: Receitas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Receitas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulo,Preparo")] Receita receita)
        {
            if (ModelState.IsValid)
            {
                _context.Add(receita);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(receita);
        }

        // GET: Receitas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receita = await _context.Receita.FindAsync(id);
            if (receita == null)
            {
                return NotFound();
            }
            return View(receita);
        }

        // POST: Receitas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,Preparo")] Receita receita)
        {
            if (id != receita.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(receita);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReceitaExists(receita.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(receita);
        }

        // GET: Receitas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var receita = await _context.Receita
                .FirstOrDefaultAsync(m => m.Id == id);
            if (receita == null)
            {
                return NotFound();
            }

            return View(receita);
        }

        // POST: Receitas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var receita = await _context.Receita.FindAsync(id);
            _context.Receita.Remove(receita);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReceitaExists(int id)
        {
            return _context.Receita.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

@*<div class="text-center">
    <h1 class="display-4">Seja bem-vindo</h1>
    <a asp-controller="Receitas" asp-action="Index">Ir para receitas</a>
</div>*@


<div class="jumbotron">
    <div class="container">
        <h1 class="display-2">Receitas Web</h1>
        <p class="lead">Seja bem-vindo ao seu site de receitas!</p>
        <hr/>
        <a class="btn btn-outline-info" asp-controller="Receitas" asp-action="Index">Clique aqui para ter acesso à lista de receitas.</a>
    </div>
</div>

Views/Receita/Index.cshtml
@{ 
    ViewData["Title"] = "Lista de Receitas";
}

<h2>Minha lista de receitas</h2>

<p>Olá Aspnet</p>

Views/Receita/Welcome.cshtml
@{ 
    ViewData["Title"] = "Bem-vindo!";
}

<h2>Seja bem-vindo</h2>

<ul>
    @for (int i = 0; i < (int)ViewData["NumTimes"]; i++)
            {
                <li>@ViewData["Message"]</li>
            }
</ul>

Views/Receitas/Create.cshtml
@model ReceitasMvc.Models.Receita

@{
    ViewData["Title"] = "Criar";
}

<h1>Adicionar</h1>

<h4>Nova receita</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preparo" class="control-label"></label>
                <textarea asp-for="Preparo" class="form-control" rows="5"></textarea>
                <span asp-validation-for="Preparo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para a lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Receitas/Delete.cshtml
@model ReceitasMvc.Models.Receita

@{
    ViewData["Title"] = "Deletar";
}

<h1>Apagar</h1>

<h3>Você tem certeza que quer apagar este registro?</h3>
<div>
    <h4>Receita</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preparo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preparo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar para lista</a>
    </form>
</div>

Views/Receitas/Details.cshtml
@model ReceitasMvc.Models.Receita

@{
    ViewData["Title"] = "Detalhes";
}

<h1>Detalhes</h1>

<div>
    <h4>Receita</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Preparo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Preparo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
    <a asp-action="Index">Voltar para lista</a>
</div>

Views/Receitas/Edit.cshtml
@model ReceitasMvc.Models.Receita

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Receita</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preparo" class="control-label"></label>
                <input asp-for="Preparo" class="form-control" />
                <span asp-validation-for="Preparo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Receitas/Index.cshtml
@model IEnumerable<ReceitasMvc.Models.Receita>

@{
    ViewData["Title"] = "Receitas";
}

<h1 class="display-3">Lista de receitas</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Criar nova receita</a>
</p>

<form asp-controller="Receitas" asp-action="Index" method="get">
    <p>
        Título: <input type="text" name="SearchString" />
        <input type="submit" value="Filtrar" />
    </p>

</form>


@foreach (var item in Model)
{

    <div class="row mt-3">
        <div class="col-sm-8 card border-dark"> 
            <div class="card-body">
                <div class="card-title h1 border-bottom">
                    @Html.DisplayFor(modelItem => item.Titulo)
                </div>
                <div class="card-text">
                    @Html.DisplayFor(modelItem => item.Preparo)
                </div>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info mr-1">Editar</a>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-success mr-1">Detalhes</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger mr-1">Deletar</a>
            </div>
        </div>
            
    </div>

  

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Receitas Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Receitas</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container">
            &copy; 2022 - Receitas Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>